name: update_release_notes

on:
  push:
    branches:
      - master
  
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: run-script
        run: ls -al
