name: update_release_notes

on:
  push:
    branches:
      - master
  
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Update release notes
        run: echo "test ${{ steps.vars.output.sha_short }}" >> test.txt
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-release-notes-${{ steps.vars.outputs.sha_short }}
          delete-branch: true
          commit-message: Update release notes for ${{ steps.vars.outputs.sha_short }}
          title: Update release notes for ${{ steps.vars.outputs.sha_short }}
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"

