name: update_release_notes

on:
  push:
    tags:
      - 'v*'
  
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Get version
#        id: vars
#        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Update release notes
        run: echo "test $GITHUB_REF" >> test.txt
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-release-notes-$GITHUB_REF
          delete-branch: true
          commit-message: Update release notes for $GITHUB_REF
          title: Update release notes for $GITHUB_REF
          base: master
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"

