name: update_release_notes

on:
  push:
    tags:
      - 'v*'
  
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        id: vars
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Update release notes
        run: echo "test ${{ steps.vars.outputs.VERSION }}" >> test.txt
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-release-notes-${{ steps.vars.outputs.VERSION }}
          delete-branch: true
          commit-message: Update release notes for ${{ steps.vars.outputs.VERSION }}
          title: Update release notes for ${{ steps.vars.outputs.VERSION }}
          base: master
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"

